# Generated by Django 2.2.4 on 2019-08-14 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='alarm',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
