# Generated by Django 2.2.4 on 2019-08-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_auto_20190814_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
