# Generated by Django 2.2.4 on 2019-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0006_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
    ]
