# Generated by Django 2.2.4 on 2019-08-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0007_alarm_tracked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='tracked',
        ),
    ]
